### ISSUE TITLE
TaskDialog fails with ArgumentException on 64bit OS.

### ISSUE THREAD

**Issue by slowik-marcin** [dahall/Vanara#118]
**Describe the bug**
I tried to use TaskDialog in a 64bit WPF application on Win 7 64bit and Win 10 64bit. and I got ArgumentException.
When I switched to 32bit (using "Prefer 32 bit" option) it works as expected.

```
System.ArgumentException: Value does not fall within the expected range.
at Vanara.Windows.Forms.TaskDialog.PrivateShow(HWND hwndOwner) in C:\Users\dahall\Documents\GitHubRepos\Vanara\Windows.Forms\Dialogs\TaskDialog\TaskDialog.cs:line 1227
at Vanara.Windows.Forms.TaskDialog.RunDialog(IntPtr hwndOwner) in C:\Users\dahall\Documents\GitHubRepos\Vanara\Windows.Forms\Dialogs\TaskDialog\TaskDialog.cs:line 1113
at System.Windows.Forms.CommonDialog.ShowDialog(IWin32Window owner)
```

**What code is involved**
I'm using the latest version, 3.2.6.
```
var td = new TaskDialog(); 
 td.ShowDialog();
```

**Expected behavior**
A dialog would appear.

**Screenshots**
None.

**Comment by dahall** [comment]
Easy fix, hard to find. Thanks for submitting. It will go out in the next release (3.2.7). If you need a build prior to full release, please see project homepage for info about AppVeyor NuGet source.
