### ISSUE TITLE
Failing tests with .NET 4.8

### ISSUE THREAD

**Issue by NN---** [dahall/Vanara#145]
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Vanara.InteropServices.IntPtrConverter.Convert(IntPtr ptr, UInt32 sz, Type destType, CharSet charSet) in Vanara\Core\InteropServices\IntPtrConverter.cs:line 46
   at Vanara.PInvoke.Collections.UntypedNativeMemoryEnumerator.get_Current() in Vanara\Core\Collections\NativeMemoryEnumerator.cs:line 90
   at Vanara.PInvoke.Collections.NativeMemoryEnumerator`1.get_Current() in Vanara\Core\Collections\NativeMemoryEnumerator.cs:line 25
   at Vanara.Extensions.Tests.InteropExtensionsTests.ToIEnumTest() in Vanara\UnitTests\Core\Extensions\InteropExtensionsTests.cs:line 203

```

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Vanara.InteropServices.IntPtrConverter.Convert(IntPtr ptr, UInt32 sz, Type destType, CharSet charSet) in Vanara\Core\InteropServices\IntPtrConverter.cs:line 46
   at Vanara.PInvoke.Collections.UntypedNativeMemoryEnumerator.get_Current() in Vanara\Core\Collections\NativeMemoryEnumerator.cs:line 90
   at Vanara.PInvoke.Collections.NativeMemoryEnumerator`1.get_Current() in Vanara\Core\Collections\NativeMemoryEnumerator.cs:line 25
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Vanara.Extensions.Tests.InteropExtensionsTests.MarshalToPtrTest3() in Vanara\UnitTests\Core\Extensions\InteropExtensionsTests.cs:line 147
```

**Comment by ljani** [comment]
I'm on .NET Core 3.1.301 and for example [`EnumServicesStatusEx`](https://github.com/dahall/Vanara/blob/c88bf0acfd4e0b209b5ed6d2d688fd22a1aad37a/PInvoke/Security/AdvApi32/WinSvc.cs#L3259) returns fails with `System.NullReferenceException` as well.

**Comment by dahall** [comment]
@NN--- : I have fixed these (see notes on commits)
@ljani : What parameters are causing that error?

**Comment by ljani** [comment]
Both `EnumServicesStatusEx(manager, AdvApi32.ServiceTypes.SERVICE_WIN32, AdvApi32.SERVICE_STATE.SERVICE_STATE_ALL)` and `EnumServicesStatusEx(manager, AdvApi32.ServiceTypes.SERVICE_TYPE_ALL, AdvApi32.SERVICE_STATE.SERVICE_STATE_ALL)
` fail.

Copy pasting the code and changing `mem.ToEnumerable<ENUM_SERVICE_STATUS_PROCESS>` to `mem.ToArray<ENUM_SERVICE_STATUS_PROCESS>` fixes the issue for me.
