### ISSUE TITLE
`SafeProcThreadAttributeList.Create` with `PROC_THREAD_ATTRIBUTE_HANDLE_LIST` fails with a marshalling exception

### ISSUE THREAD

**Issue by ashmind** [dahall/Vanara#249]
**Describe the bug**
Using `SafeProcThreadAttributeList.Create` with `PROC_THREAD_ATTRIBUTE.PROC_THREAD_ATTRIBUTE_HANDLE_LIST` throws an exception from `Marshal.SizeOf`, probably for any contents of the list.
```
System.ArgumentException: Type 'Vanara.PInvoke.HANDLE[]' cannot be marshaled as an unmanaged structure; no meaningful size or offset can be computed.
   at System.Runtime.InteropServices.Marshal.SizeOfHelper(Type t, Boolean throwIfNotMarshalable)
   at System.Runtime.InteropServices.Marshal.SizeOf(Object structure)
   at Vanara.PInvoke.Kernel32.SafeProcThreadAttributeList.Add(PROC_THREAD_ATTRIBUTE attr, Object value) in Vanara\PInvoke\Kernel32\ProcessThreadsApi.cs:line 7571
   at Vanara.PInvoke.Kernel32.SafeProcThreadAttributeList.Create(IDictionary`2 attributes) in Vanara\PInvoke\Kernel32\ProcessThreadsApi.cs:line 7541
```

**What code is involved**
`Vanara.PInvoke.Kernel32.SafeProcThreadAttributeList.Create`, for example:
```csharp
SafeProcThreadAttributeList.Create(new Dictionary<PROC_THREAD_ATTRIBUTE, object>
{
    { PROC_THREAD_ATTRIBUTE.PROC_THREAD_ATTRIBUTE_HANDLE_LIST, new HANDLE[0] }
});
```

Updated test case `SafeProcThreadAttributeListTest`:
```csharp
[Test]
public void SafeProcThreadAttributeListTest()
{
	Assert.That(PROC_THREAD_ATTRIBUTE.PROC_THREAD_ATTRIBUTE_HANDLE_LIST, Is.EqualTo(new UIntPtr(0x20002)));
	Assert.That(() =>
	{
		var l = SafeProcThreadAttributeList.Create(new Dictionary<PROC_THREAD_ATTRIBUTE, object>
		{
			{PROC_THREAD_ATTRIBUTE.PROC_THREAD_ATTRIBUTE_IDEAL_PROCESSOR, new PROCESSOR_NUMBER(0, 2) },
			{PROC_THREAD_ATTRIBUTE.PROC_THREAD_ATTRIBUTE_MITIGATION_POLICY, 0x00000001UL },
			// Added this line
			{PROC_THREAD_ATTRIBUTE.PROC_THREAD_ATTRIBUTE_HANDLE_LIST, new HANDLE[0] },
		});
		l.Dispose();
	}, Throws.Nothing);
}
```

**Expected behavior**
`SafeProcThreadAttributeList` is created successfully with a correct pointer to the handle array.

**Comment by dahall** [comment]
Thanks for catching this. There was a bug in the `Add` method. I have just posted the fix. The use case you modified actually needs real process handles as follows:
```cs
[Test]
public void SafeProcThreadAttributeListTest()
{
   Assert.That(PROC_THREAD_ATTRIBUTE.PROC_THREAD_ATTRIBUTE_HANDLE_LIST, Is.EqualTo(new UIntPtr(0x20002)));
   Assert.That(() =>
   {
      using var p2 = CreateProcess("cmd.exe");
      var l = SafeProcThreadAttributeList.Create(new Dictionary<PROC_THREAD_ATTRIBUTE, object>
      {
         {PROC_THREAD_ATTRIBUTE.PROC_THREAD_ATTRIBUTE_IDEAL_PROCESSOR, new PROCESSOR_NUMBER(0, 2) },
         {PROC_THREAD_ATTRIBUTE.PROC_THREAD_ATTRIBUTE_MITIGATION_POLICY, 0x00000001UL },
         {PROC_THREAD_ATTRIBUTE.PROC_THREAD_ATTRIBUTE_HANDLE_LIST, new HANDLE[] { p2 } },
      });
      l.Dispose();
      p2.Close();
   }, Throws.Nothing);
}
```
This will go out in version 3.3.13 or is available now on the AppVeyor feed described on the home page.
