### ISSUE TITLE
Incorrect CIDA offset handling

### ISSUE THREAD

**Issue by billybednar** [dahall/Vanara#268]
**Describe the bug**
`CIDA.offsets` is treating `CIDA.aoffset` as a pointer to an array, but it is actually the first element of the array. This results in an access violation while attempting to read low memory. See [here](https://github.com/dahall/Vanara/blob/8ca58cc2c8d5ca87c19a434f06b6b2f6810aa313/PInvoke/Shell32/Clipboard.cs#L113-L134).

**Example**
An access violation occurs at the marked line when dragging a file or folder into the following form.
```csharp
using System;
using System.Diagnostics;
using System.IO;
using System.Windows.Forms;
using Shell32 = Vanara.PInvoke.Shell32;

class TestForm : Form
{
    public TestForm() => AllowDrop = true;

    [System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptions]
    protected unsafe override void OnDragEnter(DragEventArgs drgevent)
    {
        base.OnDragEnter(drgevent);
        if (!drgevent.Data.GetDataPresent("Shell IDList Array"))
            return;
        using (var ms = (MemoryStream)drgevent.Data.GetData("Shell IDList Array"))
        using (var pinnedBuf = new Vanara.InteropServices.PinnedObject(ms.ToArray()))
        {
            var cida = (Shell32.CIDA*)(IntPtr)pinnedBuf;
            Debug.WriteLine(cida->cidl); // 1
            Debug.WriteLine(cida->aoffset); // 12
            try
            {
                Debug.WriteLine(string.Join(", ", cida->offsets)); // access violation here
            }
            catch (AccessViolationException ex)
            {
                // Access violation does not cause crash or debugger break for unknown reason, so catch
                // it and print out details
                Debug.WriteLine(ex.ToString());
                throw;
            }
            using (Shell32.PIDL folder = cida->GetFolderPIDL()) // would get an access violation here
                Debug.WriteLine(folder.ToString());
        }
    }
}
```

**Output:**
```
1
12
Exception thrown: 'System.AccessViolationException' in mscorlib.dll
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr ptr, Object structure, Boolean allowValueClasses)
   at System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr ptr, Type structureType)
   at Vanara.Extensions.InteropExtensions.GetValueType(IntPtr ptr, Type type, Type trueType, Int32 offset, SizeT allocatedBytes)
   at Vanara.InteropServices.IntPtrConverter.Convert(IntPtr ptr, UInt32 sz, Type destType, CharSet charSet)
   at Vanara.Extensions.InteropExtensions.ToArray(IntPtr ptr, Type type, Int32 count, Int32 prefixBytes, SizeT allocatedBytes)
   at Vanara.PInvoke.Shell32.CIDA.get_offsets()
   at TestForm.OnDragEnter(DragEventArgs drgevent) in C:\path\to\TestForm.cs:line 25
Exception thrown: 'System.AccessViolationException' in Program.exe
```

Also, is there a better way to get a `CIDA` instance out of an `IDataObject`?

**Comment by dahall** [comment]
Thanks for pointing this out. I'll get it corrected soon. I'm in a major redo of the library as a whole to remove a lot of dependencies on WinForms and System.Drawing. This really affects the Shell32 and Shell libraries. You'll see them all in the 3.4.0 release.

It looks like you're trying to get the ShellItems off the clipboard. If that is the case, check out the ShellDataObject class in the Vanara.Windows.Shell library.

**Comment by dahall** [comment]
I think I've corrected the issue, but if you're on an OS Vista or later, you should consider using `SHCreateShellItemArrayFromDataObject` instead of processing `CIDA` manually.
