### ISSUE TITLE
Shell32.SHChangeNotify: exception when called

### ISSUE THREAD

**Issue by stefan-agl** [dahall/Vanara#269]
Greetings, 

Following an example from MS, I am trying to do similar via respective P/Invoke methods from this library. 

C++ sample code: 
https://github.com/microsoft/Windows-classic-samples/blob/main/Samples/CloudMirror/CloudMirror/ContextMenus.cpp#L76

There, they have an invocation which goes like this: 

` SHChangeNotify(SHCNE_UPDATEITEM, SHCNF_PATH, static_cast<void*>(fullPath.data()), nullptr); `

On my side I am trying to mimic this in the following way

`      
        await StorageProviderItemProperties.SetAsync(storageItem, properties);
        // absPath  is  defined as "string absPath"
        using var pidl = new Shell32.PIDL(absPath);
        Shell32.SHChangeNotify(Shell32.SHCNE.SHCNE_UPDATEITEM, Shell32.SHCNF.SHCNF_PATHW, pidl);
`

Ultimately, I would like to have an opened Explorer window refresh the row for a file whose properties changed (i.e. state icon changes due to actions performed) 

This call, however, results in an exception on my side: 

`
System.ArgumentNullException
  HResult=0x80004003
  Message=SafeHandle cannot be null. (Parameter 'pHandle')
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument, ExceptionResource resource) in /_/src/libraries/System.Private.CoreLib/src/System/ThrowHelper.cs:line 229
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success) in /_/src/coreclr/src/System.Private.CoreLib/src/System/StubHelpers.cs:line 1274
   at Vanara.PInvoke.Shell32.SHChangeNotify(SHCNE wEventId, SHCNF uFlags, PIDL dwItem1, PIDL dwItem2)
   at --my assembly name--.<SetFileStateIcon>d__22.MoveNext() in C:\-- full source path --\SyncEngine.cs:line 449
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 56
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 1898
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPool.cs:line 856
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPool.cs:line 677

  This exception was originally thrown at this call stack:
    System.ThrowHelper.ThrowArgumentNullException(System.ExceptionArgument, System.ExceptionResource) in ThrowHelper.cs
    System.StubHelpers.StubHelpers.SafeHandleAddRef(System.Runtime.InteropServices.SafeHandle, ref bool) in StubHelpers.cs
    --my assembly name--.SetFileStateIcon(string, string) in SyncEngine.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in ExceptionDispatchInfo.cs
    System.Threading.Tasks.Task.ThrowAsync.AnonymousMethod__140_1(object) in Task.cs
    System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute() in ThreadPool.cs
    System.Threading.ThreadPoolWorkQueue.Dispatch() in ThreadPool.cs
`

Is what I have the correct way to call this method. If yes, what else may be the matter. 

Thanks, and regards,
Stefan

**Comment by dahall** [comment]
If you will specify `PIDL.Null` for the fourth param, after the `pidl` param, you should avoid the error. I need to make that fourth param non-optional in the declaration to avoid this from happening.
