### ISSUE TITLE
WinINet.InternetSetOption seems breaking change in 4.0.0

### ISSUE THREAD

**Issue by GF-Huang** [dahall/Vanara#460]
**Describe the bug and how to reproduce**
### 3.4.17

![image](https://github.com/dahall/Vanara/assets/4510984/e0bf8bae-ae9c-4d8d-bcf0-d7e2ef4dc3dc)

### 4.0.0

![image](https://github.com/dahall/Vanara/assets/4510984/ef80a8c3-d03f-4f50-aee2-0b8e03225f99)

**What code is involved**
```cs
WinINet.InternetSetOption(WinINet.HINTERNET.NULL, WinINet.InternetOptionFlags.INTERNET_OPTION_PROXY_SETTINGS_CHANGED)
```

exception:
```
Error: System.ArgumentException: INTERNET_OPTION_PROXY_SETTINGS_CHANGED cannot be used to set options that do not require a value.
at Vanara.PInvoke.WinINet.InternetSetOption(HINTERNET hInternet, InternetOptionFlags option)
at Submission#5.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```

**Expected behavior**
No exception as `3.4.17`.

**Comment by dahall** [comment]
Thank you. Fixed for 4.0.1.
