### ISSUE TITLE
Setting affinity on JobSettings throws ArgumentException if KillOnJobClose is set to true

### ISSUE THREAD

**Issue by cguedel** [dahall/Vanara#70]
**Describe the bug**
We try to set the processor affinity of a child process by using a JobObject. When calling the setter of the `Affinity` property, it throws `ArgumentException` if in a previous call the `KillOnJobClose` property was set to true.

**What code is involved**
```
static void Main(string[] args)
{
    var process = Process.Start("notepad.exe");

    var jobObject = Job.Create("foo");
    jobObject.AssignProcess(process);
    jobObject.Settings.KillOnJobClose = true; // <-- setting this to false does not cause the problem
    jobObject.Settings.Affinity = new UIntPtr(0xFFFF);
}
```

**Expected behavior**
Expect not to get the ArgumentException.

**StackTrace**
```
System.ArgumentException: Value does not fall within the expected range.
   at Vanara.PInvoke.Kernel32.SetInformationJobObject[T](HJOB hJob, JOBOBJECTINFOCLASS jobObjectInfoClass, T& jobObjectInfo)
   at Vanara.Diagnostics.Job.CheckThenSet[T](RefAction`1 action, JOBOBJECTINFOCLASS iClass)
   at Vanara.Diagnostics.JobHelper.SetBasic[T](JOBOBJECT_LIMIT_FLAGS flag, Nullable`1 value, RefAction`1 setter)
   at Vanara.Diagnostics.JobSettings.set_Affinity(Nullable`1 value)
   at CpuAffinity.Program.Main(String[] args) in C:\Users\c.guedel\source\repos\ConsoleApp12\CpuAffinity\Program.cs:line 22
```

**Comment by dahall** [comment]
Thanks for finding this. I was able to remove the exception with a simple fix that should also prevent other possible exception when both extended and basic limits are set. This will be in the next release.

**Comment by cguedel** [comment]
Wow, that was quick, thank you!
