### ISSUE TITLE
ShellLink.cs::LoadAndResolve raises COMException when processing files with .URL extension.

### ISSUE THREAD

**Issue by Yomodo** [dahall/Vanara#82]
**Describe the bug**
After implementing #81, project ExplorerBrowser can be compiled.
When ExplorerBrowser is started, it enumerates files/folders from my desktop and raises a
COM exception on files ending with the `.URL` extension.

**What code is involved**
Project `ExplorerBrowser`, Method `LoadAndResolve` in `Vanara\Windows.Shell\ShellObjects\ShellLink.cs` at line 361.

**Comment by dahall** [comment]
Please provide the details of the COMException. The error is coming from IPersistFile::Load and shouldn't happen but I need the error code to understand why.

**Comment by Yomodo** [comment]
"Error HRESULT E_FAIL has been returned from a call to a COM component."
ErrorCode: -2147467259

   at System.Runtime.InteropServices.ComTypes.IPersistFile.Load(String pszFileName, Int32 dwMode)
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut) in C:\Users\jjangli\source\repos\Vanara\Windows.Shell\ShellObjects\ShellLink.cs:line 361
   at Vanara.Windows.Shell.ShellLink..ctor(IShellItem iItem) in C:\Users\jjangli\source\repos\Vanara\Windows.Shell\ShellObjects\ShellLink.cs:line 106
   at Vanara.Windows.Shell.ShellItem.Open(IShellItem iItem) in C:\Users\jjangli\source\repos\Vanara\Windows.Shell\ShellObjects\ShellItem.cs:line 480
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.WindowsAPICodePack.Samples.ExplorerBrowserTestForm.uiDecoupleTimer_Tick(Object sender, EventArgs e) in C:\Users\jjangli\source\repos\Vanara\UnitTests\ExplorerBrowser\ExplorerBrowserTestForm.cs:line 231
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.WindowsAPICodePack.Samples.Program.Main() in C:\Users\jjangli\source\repos\Vanara\UnitTests\ExplorerBrowser\Program.cs:line 18

**Comment by dahall** [comment]
I have made changes to ShellItem.Open so that .Url files now open as files and not links to avoid the error.
